name: Rust

on:
  # push:
  #   branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        chmod +x scripts/*
        sh scripts/build.sh debug
    - name: Run tests
      run: cargo test --verbose
